UPDATE "Student"
SET "studentClass" = CASE UPPER(TRIM("className"))
                         WHEN '1' THEN 'FIRST'::"StudentClass"
                         WHEN 'I' THEN 'FIRST'::"StudentClass"
                         WHEN '2' THEN 'SECOND'::"StudentClass"
                         WHEN 'II' THEN 'SECOND'::"StudentClass"
                         WHEN '3' THEN 'THIRD'::"StudentClass"
                         WHEN 'III' THEN 'THIRD'::"StudentClass"
                         WHEN '4' THEN 'FOURTH'::"StudentClass"
                         WHEN 'IV' THEN 'FOURTH'::"StudentClass"
                         WHEN '5' THEN 'FIFTH'::"StudentClass"
                         WHEN 'V' THEN 'FIFTH'::"StudentClass"
                         WHEN '6' THEN 'SIXTH'::"StudentClass"
                         WHEN 'VI' THEN 'SIXTH'::"StudentClass"
                         WHEN '7' THEN 'SEVENTH'::"StudentClass"
                         WHEN 'VII' THEN 'SEVENTH'::"StudentClass"
                         WHEN '8' THEN 'EIGHTH'::"StudentClass"
                         WHEN 'VIII' THEN 'EIGHTH'::"StudentClass"
                         WHEN '9' THEN 'NINTH'::"StudentClass"
                         WHEN 'IX' THEN 'NINTH'::"StudentClass"
                         WHEN 'IX CLASS' THEN 'NINTH'::"StudentClass"
                         WHEN '10' THEN 'TENTH'::"StudentClass"
                         WHEN 'X' THEN 'TENTH'::"StudentClass"
                         WHEN 'X CLASS' THEN 'TENTH'::"StudentClass"
                         WHEN '11' THEN 'ELEVENTH'::"StudentClass"
                         WHEN 'XI' THEN 'ELEVENTH'::"StudentClass"
                         WHEN '12' THEN 'TWELFTH'::"StudentClass"
                         WHEN '12TH STD' THEN 'TWELFTH'::"StudentClass"
                         WHEN 'BCOM' THEN 'BCOM'::"StudentClass"
                         WHEN 'BA' THEN 'BA'::"StudentClass"
                         ELSE 'OTHER'::"StudentClass"
END;